charmed-hpc/slurm-charms

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml, .gitignore, charms/slurmctld/charmcraft.yaml, repository.py, tests/integration/test_charm.py, tox.ini
This adds another command in tox to generate a Charmhub token, which should be useful to regenerate it in an easier way.
=> ci: enable CI actions

test-requirements.txt
Fix CVE-2024-41129
Bumps ops to version 2.14.0 in our test requirements. Needed to author this PR manually as for some reason Dependabot could not parse the project _pyproject.toml_ file.
=> chore(deps): Bump ops from 2.14.0 to 2.15.0

repository.py, tests/integration/conftest.py, tests/integration/test_charm.py
Combines all the checks from the integration tests of all the charms.
=> test: add additional integration checks

charms/slurmctld/src/constants.py
These changes modify the charm maintained slurm configuration SlurmdLogFile to point to /var/log/slurm/slurmd.log.
=> chore(slurmd): SlurmdLogFile name correction

charms/slurmctld/src/charm.py, charms/slurmctld/tests/unit/test_charm.py
These changes modify the user supplied config parser so that it correctly handles nested user supplied configuration values.
Fixes #14
=> fix(slurmctld): correctly parse nested config

.editorconfig, charms/slurmctld/terraform/main.tf, charms/slurmctld/terraform/outputs.tf, charms/slurmctld/terraform/variables.tf, charms/slurmctld/terraform/versions.tf, charms/slurmd/terraform/main.tf, charms/slurmd/terraform/outputs.tf, charms/slurmd/terraform/variables.tf, charms/slurmd/terraform/versions.tf, charms/slurmdbd/terraform/main.tf, charms/slurmdbd/terraform/outputs.tf, charms/slurmdbd/terraform/variables.tf, charms/slurmdbd/terraform/versions.tf, charms/slurmrestd/terraform/main.tf, charms/slurmrestd/terraform/outputs.tf, charms/slurmrestd/terraform/variables.tf, charms/slurmrestd/terraform/versions.tf
This PR adds terraform modules for deploying the Slurm charms as part of a Charmed HPC cluster. _I need the modules published so I can verify that they work_.
These modules will enable us to declare the deployment of Slurm without needing us to manually re-define things within the `charmed-hpc-bundles` repository. For example, here's how we can pull the Slurm charm into our Charmed HPC deployment plan:
```hcl
module "controller" {
source = "git::https://github.com/charmed-hpc/slurm-charms/charms/slurmctld//terraform"
model_name = "juju_model_name"
app_name = "controller"
units = 1
}
module "compute" {
source = "git::https://github.com/charmed-hpc/slurm-charms/charms/slurmd//terraform"
model_name = "juju_model_name"
app_name = "compute"
units = 1
}
resource "juju_integration" …
```
=> feat: add terraform modules for deploying slurm charms

.github/workflows/nightly-TICS.yaml, .gitignore, repository.py
This introduces a Github action that uses the TiCS framework to send code quality statistics to TIOBE.
=> feat: introduce TiCS analysis to the repo

charms/slurmctld/charmcraft.yaml
These changes add reasonable defaults for charm `cgroup.conf`.
Fixes #31
=> feat(slurmctld): add sane defaults for cgroup.conf

.github/workflows/ci.yaml, .github/workflows/nightly-TICS.yaml, .github/workflows/release.yaml
Small fix to make the CI actions work again.
=> fix: use pipx and virtual environments for CI actions

charms/slurmctld/src/charm.py
This PR fixes the *resume* action in the *slurmctld* charm. The source error can be seen on [this](https://app.warp.dev/block/MxGNPLvRGpmjegds477jJz) link.
Essentially, the command to resume the nodes has been patched from `scontrol update nodename=<names> state=resume` to `scontrol update nodename=<names> state=idle`.
As I understand [Slurm's documentation](https://slurm.schedmd.com/scontrol.html#OPT_RESUME), there's no operational change applied by this PR.
=> Fix the resume action in the slurmctld charm

charms/slurmctld/build.yaml, charms/slurmctld/charmcraft.yaml, charms/slurmctld/src/charm.py, charms/slurmctld/src/cos/alert_rules/prometheus/high_cpu_usage.rule, charms/slurmctld/src/cos/alert_rules/prometheus/unreachable_slurmdbd.rule, charms/slurmctld/src/cos/grafana_dashboards/slurm.json, charms/slurmctld/tests/unit/test_charm.py, external/lib/charms/grafana_agent/v0/cos_agent.py, test-requirements.txt
This PR adds in the original COS-related patches from the `experimental` branch of the Slurm charms, but with an extra dose of Slurm back-end support provided by the `slurm_ops` charm library. This means that COS both now works with the Slurm snap and Slurm Debian package. 
This is a bit more difficult to write integration tests for as microk8s + LXD will quickly overwhelm your average GitHub runner, but the next steps are to create a COS-lite/Grafana Terraform module that can be used by `charmed-hpc-terraform` to deploy the Slurm charms with COS if desired. Here's what the default dashboard looks like currently on Grafana:
* Fix the publishing CI.
* Cache charm builds so they go faster in CI.
* Add grafana-agent to Charmed HPC's Terraform plan.
* Add more dashboards + understand what …
=> feat(slurmctld): enable `cos-agent` for metrics collection from Slurm cluster

.github/workflows/release.yaml
This PR sets the `destructive-mode` option for the `upload-charm` action to false. Pulling the down the base LXD instance will add some extra time onto the workflow run, but it make us not be dependent on the base OS of the GitHub runner VM to release the Slurm charms. This is especially helpful for it we need to release multiple the Slurm charms with support for multiple bases. Eventually we'll either want to replace the `cryptography` dependency that takes so long to build, or use the `ccc` tool to cache the Slurm charms dependencies so that the build for them is quicker.
Just for added insurance, I also updated the `CHARMCRAFT_AUTH` secret.
* Fixes #39
=> fix(ci): do not use destructive packing when building charms for release

charms/slurmctld/charmcraft.yaml, charms/slurmctld/src/charm.py, charms/slurmctld/src/interface_slurmd.py, charms/slurmctld/tests/unit/test_charm.py, charms/slurmd/src/interface_slurmctld.py
These changes remove the unused "cluster_name" from the relation data sent to `slurmd` on the `slurmd` relation. Additionally, make the "cluster_name" property private.
=> chore(slurmctld, slurmd): clean up relation data

.github/workflows/release.yaml
The `upload-charm` action does not initialize LXD which will cause the worklflow to fail if destructive-mode is set to false.
This PR is a follow-on fix for https://github.com/charmed-hpc/slurm-charms/pull/42 since the `upload-charm` action doesn't set up LXD itself.
=> fix(ci): initialize lxd before packing charm

charms/slurmctld/charmcraft.yaml, charms/slurmctld/src/charm.py, charms/slurmctld/src/constants.py, charms/slurmctld/src/exceptions.py, charms/slurmctld/src/interface_slurmd.py, charms/slurmctld/tests/unit/test_charm.py, charms/slurmd/src/charm.py, charms/slurmd/src/constants.py, charms/slurmd/src/interface_slurmctld.py
These changes introduce default values for `SelectTypeParameters` and `MemSpecLimit`.
`SelectTypeParameters=CR_CPU_Memory` to enable memory allocation enforcement.
`MemSpecLimit=1024` to ensure systems always have 1G available memory that jobs cannot consume.
Fixes: #36
=> enhancement(slurmctld): Make slurm respect memory constraints

charms/slurmctld/charmcraft.yaml, charms/slurmctld/src/charm.py, charms/slurmctld/src/constants.py
These changes move the cgroup config to the charm constants.py.
=> chore(slurmctld): charm maintained cgroup config

charms/slurmctld/src/charm.py, charms/slurmctld/tests/unit/test_charm.py
This PR splits the argument passed to `_slurmctld.scontrol` in `_resume_nodes` to fix a subsequent erroneous subprocess.run call in hpc-libs. Specifically, subprocess.run was being passed:
` ['scontrol', 'update nodename=<nodes> state=resume']`
rather than (the now corrected):
` ['scontrol', 'update', 'nodename=<nodes>', 'state=resume']`
A unit test for `_resume_nodes` has also been added.
This fixes `juju run slurmd/<id> node-configured` so `hook failed: "slurmd-relation-changed"` is no longer reported. Edit: Added the relevant log lines for the hook failure from the `slurmctld/0` log `/var/log/juju/unit-slurmctld-0.log`:
<details>
<summary>/var/log/juju/unit-slurmctld-0.log reported failure</summary>
```
2024-12-06 09:24:49 ERROR unit.slurmctld/0.juju-log server.go:325 slurmd:0: command …
```
=> fix(slurmctld): fix node-configured action

.github/workflows/release.yaml
This PR adds `sackd` to the charm release matrix in the "Release to latest/edge" workflow. This will ensure that `sackd` is published to Charmhub after each PR.
Also, treat `charmhub` as a proper noun in step names. `charmhub` -> `Charmhub`.
=> feat(ci): add `sackd` to release matrix

README.md
This PR adds instructions for how to deploy and integrate sackd with slurmctld. Also adds a short bullet about what sackd is.
* Move badges to be under the README header.
* Add project license badge.
=> docs(all): add section for `sackd`

.gitignore, charms/sackd/terraform/README.md, charms/sackd/terraform/main.tf, charms/sackd/terraform/variables.tf, charms/slurmctld/terraform/README.md, charms/slurmctld/terraform/main.tf, charms/slurmctld/terraform/variables.tf, charms/slurmd/terraform/README.md, charms/slurmd/terraform/main.tf, charms/slurmd/terraform/variables.tf, charms/slurmdbd/terraform/README.md, charms/slurmdbd/terraform/main.tf, charms/slurmdbd/terraform/variables.tf, charms/slurmrestd/terraform/README.md, charms/slurmrestd/terraform/main.tf, charms/slurmrestd/terraform/variables.tf
This PR adds the `base` and `constraints` configuration options to the Slurm charm tf modules. This way we can specify different bases, and request specific instance types through OpenTofu/Terraform. This PR also adds READMEs for each of the modules to document both inputs and outputs.
=> feat(all): add `base` and `constraints` config options to charm tf modules

.github/workflows/ci.yaml, .github/workflows/release.yaml
This should fix the CI issues we've been seeing since charmcraft 3.3.2 was released to the `latest/stable` channel. I just modified the CI and Release pipelines to just install and hold the version of charmcraft to 3.2.3. We'll still need to deep dive on what the longer term solution is, but at least we will be able to get the latest batch of PRs through.
Bug opened on the upstream `charmcraft` repository:
* https://github.com/canonical/charmcraft/issues/2125
=> fix(ci): pin charmcraft to version 3.2.3

charms/slurmd/src/charm.py, charms/slurmd/src/utils/rdma.py, charms/slurmd/tests/unit/test_charm.py
This PR enables use of Infiniband in Charmed HPC clusters. Microsoft Azure `Standard_HB120rs_v3` instances equipped with 200 Gb/sec HDR InfiniBand have been used for testing.
Minimally, installing the `rdma-core` package from the Ubuntu repositories is sufficient to enable connectivity as MLNX drivers for ConnectX cards are available out-of-the-box. Here, `infiniband-diags` is also installed to provide diagnostic tools `ibstat`, `ibping`, etc. for cluster administrators.
These changes also re-enable UCX for OpenMPI. The developer-intended default for OpenMPI is to [use the UCX PML when Infiniband devices are available](https://github.com/open-mpi/ompi/blob/v4.1.x/README#L763) however, [a Debian patch](https://sources.debian.org/src/openmpi/4.1.4-3/debian/patches/no-warning-unused.patch/) …
=> feat(slurmd): enable Infiniband RDMA support

charms/slurmd/src/charm.py, charms/slurmd/src/utils/gpu.py, charms/slurmd/tests/unit/test_charm.py
Adds additional status messages as `slurmd` installs to better inform users of progress.
Changes [`WaitingStatus`](https://ops.readthedocs.io/en/latest/reference/ops-testing.html#ops.testing.WaitingStatus) to [`MaintenanceStatus`](https://ops.readthedocs.io/en/latest/reference/ops-testing.html#ops.testing.MaintenanceStatus) to follow ops docs recommendations that the former be used for waiting for "activity on related units, not on this unit" and the latter for "when the charm is performing an operation such as `apt install`".
@AshleyCliff thoughts on status messages would be appreciated!
=> Improve unit status reporting in `slurmd` install hook

tests/integration/test_charm.py
Equivalent to https://github.com/charmed-hpc/filesystem-charms/pull/12 for `slurm-charms`.
Rewrites the integration tests to build the charms concurrently.
=> tests: speedup integration tests

charms/slurmctld/src/charm.py, charms/slurmctld/src/cos/grafana_dashboards/slurm.json, external/lib/charms/hpc_libs/v0/slurm_ops.py, tests/integration/test_charm.py
Bumps `slurm_ops` to v0.18.
Adds many dashboards to our exposed grafana dashboards.
Adjusts the integration tests to check that the prometheus exporter is active.
The dashboards are based on the [dashboards offered by Rivos](https://grafana.com/grafana/dashboards/19835-slurm-dashboardv2), but with some patches to make them compatible with COS.
Some screenshots of the new dashboards:
Fixes #87.
Internal enhancement that doesn't require documentation changes.
=> feat: improve Grafana dashboards

charms/sackd/charmcraft.yaml, charms/sackd/pyproject.toml, charms/sackd/src/charm.py, charms/sackd/tests/unit/test_charm.py, charms/slurmctld/charmcraft.yaml, charms/slurmctld/pyproject.toml, charms/slurmctld/src/charm.py, charms/slurmctld/tests/unit/test_charm.py, charms/slurmd/pyproject.toml, charms/slurmd/src/charm.py, charms/slurmd/tests/unit/test_charm.py, charms/slurmdbd/charmcraft.yaml, charms/slurmdbd/pyproject.toml, charms/slurmdbd/src/charm.py, charms/slurmdbd/tests/unit/test_charm.py, charms/slurmrestd/charmcraft.yaml, charms/slurmrestd/pyproject.toml, charms/slurmrestd/src/charm.py, charms/slurmrestd/tests/unit/test_charm.py, pyproject.toml, uv.lock
Migrates all our charms from using the charm libraries from `hpc-libs` to use the `hpc-libs` python package.
Change is entirely internal, so it doesn't need documentation changes.
=> chore: migrate charms to `hpc-libs` charm library

charms/sackd/charmcraft.yaml, charms/slurmctld/charmcraft.yaml, charms/slurmd/charmcraft.yaml, charms/slurmdbd/charmcraft.yaml, charms/slurmrestd/charmcraft.yaml, pyproject.toml, uv.lock
Fixes both our CI and our integration tests by specifying Rust-based dependencies as binary python packages to avoid requiring rustc.
Internal fix which shouldn't need documentation.
=> fix: specify maturin-based dependencies to fix build

charms/slurmd/src/charm.py
~Depends on #91~
Fixes a bug where nodes would always return 1024 as their `MemSpecLimit`, even if they had less than 1024 MB of memory.
Internal change.
=> fix: set MemSpecLimit to always be less than RealMemory

charms/sackd/charmcraft.yaml, charms/slurmctld/charmcraft.yaml, charms/slurmctld/pyproject.toml, charms/slurmd/charmcraft.yaml, charms/slurmrestd/charmcraft.yaml, pyproject.toml, repository.py, uv.lock
Adds functionality on `repository.py` to inject the required binary packages onto the `charmcraft.yaml` files instead of having to manually manage them.
Internal tooling improvement, which doesn't require documentation.
=> feat: automatically manage binary packages from repository.py

charms/slurmd/src/utils/rdma.py
Single line fix to replace a logging `warn` call with `warning` as the former [is deprecated](https://docs.python.org/3/library/logging.html#logging.Logger.warning).
[//]: # (Please link to related issues, pull requests, and discussions here. If your PR has no related issues, PRs, or discussions, please provide a justification for this PR here instead.)
[//]: # (If documentation has been updated or added in a …
=> fix: replace deprecated logger `warn` method

charms/sackd/src/charm.py, charms/slurmctld/charmcraft.yaml, charms/slurmctld/src/charm.py, charms/slurmctld/src/constants.py, charms/slurmctld/src/interface_sackd.py, charms/slurmctld/src/interface_slurmd.py, charms/slurmctld/src/interface_slurmdbd.py, charms/slurmctld/src/interface_slurmrestd.py, charms/slurmctld/tests/unit/test_charm.py, charms/slurmd/charmcraft.yaml, charms/slurmd/src/charm.py, charms/slurmd/src/interface_slurmctld.py, charms/slurmdbd/charmcraft.yaml, charms/slurmdbd/src/charm.py, charms/slurmdbd/src/constants.py, charms/slurmdbd/src/interface_slurmctld.py, charms/slurmdbd/tests/unit/test_charm.py, charms/slurmrestd/charmcraft.yaml, charms/slurmrestd/src/charm.py, charms/slurmrestd/src/interface_slurmctld.py, pyproject.toml, tests/integration/test_charm.py, uv.lock
~Depends on https://github.com/charmed-hpc/hpc-libs/pull/81~
Migrates all charms to use the Slurm Auth and Cred Kiosk (SACK) subsystem (`auth/slurm`, `cred/slurm`) for authentication, removing the need to use the MUNGE service to handle authentication.
- https://github.com/charmed-hpc/docs/pull/60
=> feat: migrate charms from auth/munge to auth/slurm

charms/sackd/terraform/versions.tf, charms/slurmctld/terraform/versions.tf, charms/slurmd/terraform/versions.tf, charms/slurmdbd/terraform/versions.tf, charms/slurmrestd/terraform/versions.tf
Bumps the Juju terraform provider version to 0.19.0.
Just an internal change.
=> chore: bump juju terraform provider version

.github/workflows/nightly-TICS.yaml
Fixes our CI for the TiCS scan by installing charmcraft before running the unit tests.
Just a CI fix.
=> ci: install charmcraft before running the TiCS scan

pyproject.toml, repository.py, tests/integration/assets/sbatch_sleep_job.sh, tests/integration/conftest.py, tests/integration/constants.py, tests/integration/test_charm.py, tests/integration/test_influxdb.py, tests/integration/testdata/sbatch_sleep_job.sh, uv.lock
This PR migrates the Slurm charm integration tests to [`jubilant`](https://canonical-jubilant.readthedocs-hosted.com) from `pytest-operator` + `python-libjuju`. `jubilant` offers several advantages over `pytest-operator` such as not relying on web sockets to communicate with the Juju controller or require obfuscated `async` calls wrapped by `tenacity`.
Changes in this PR include:
- Migrating all integration tests …
=> feat: migrate integration tests to `jubilant` from `pytest-operator`

charms/sackd/src/charm.py, charms/sackd/src/constants.py, charms/slurmctld/src/charm.py, charms/slurmctld/src/constants.py, charms/slurmd/src/charm.py, charms/slurmd/src/constants.py, charms/slurmdbd/src/charm.py, charms/slurmdbd/src/constants.py, charms/slurmrestd/src/charm.py, charms/slurmrestd/src/constants.py
These changes add the open_port() to the end of the install hook for each of; slurmctld, slurmd, slurmdbd, slurmrestd, sackd.
These changes are needed to facilitate the charm creating security group rules that will allow traffic to the slurm services.
Fixes: https://github.com/charmed-hpc/slurm-charms/issues/103
[//]: # (Please link to related issues, pull requests, and discussions here. If your PR has no related …
=> (feat): open slurm service ports

README.md
Small change to remove the language in the URL for our documentation.
cc @AshleyCliff.
The PR itself is a docs change.
=> chore: remove `en` from documentation URL

charms/slurmctld/src/charm.py, charms/slurmctld/tests/unit/test_charm.py
These changes merge the values of the slurm config dict prior to passing it as input to SlurmConfig and add a test for setting user supplied slurm config that overrides slurm config set by the charm.
Fixes: #106
[//]: # (Please link to related issues, pull requests, and discussions here. If your PR has no related issues, PRs, or discussions, please provide a justification for this PR here instead.)
[//]: # (If …
=> fix: merge slurm_conf before calling SlurmConfig

charms/slurmdbd/charmcraft.yaml, charms/slurmdbd/src/charm.py, charms/slurmdbd/src/exceptions.py, charms/slurmdbd/tests/unit/test_charm.py
These changes fix #114 and #115 by a) adding the
missing slurmdbd-conf-parameters config option in slurmdbd (#114), and b) fix the dict merging error (#115).
Notes:
- The slurmdbd-peer relation was added to facilitate getting the ingress-address.
[//]: # (Please link to related issues, pull requests, and discussions here. If your PR has no related issues, PRs, or discussions, please provide a justification for …
=> fix(slurmdbd): user supplied configuration

CONTRIBUTING.md, pyproject.toml, repository.py
This PR adds support for internal Python packages in the monorepo, which makes it really simple to share common code between all the charms.
NOTE: There really wasn't a good place to put "internal" maintainer documentation, so I put the guide on how to create a new internal library into `CONTRIBUTING.md`. Let me know if you have a better place to put that.
=> feat: add support for internal Python packages in repository.py

charms/slurmctld/charmcraft.yaml, charms/slurmctld/src/charm.py, charms/slurmctld/src/constants.py, charms/slurmctld/tests/unit/conftest.py, charms/slurmctld/tests/unit/test_charm.py, tests/integration/constants.py, tests/integration/test_oci_runtime.py
This PR adds OCI runtime to support to the Slurm charms. Now that we have the interface changes merged, it was straightforward to integrate the `slurm-oci-runtime` interface implementation into the charms. To test these changes without running the full integration test suite:
```
just repo build sackd slurmctld slurmd
juju deploy ./_build/sackd.charm
juju deploy ./_build/slurmctld.charm
juju deploy …
```
=> feat(slurmctld): add `slurm-oci-runtime` integration

.github/workflows/ci.yaml, charms/slurmctld/src/charm.py, charms/slurmctld/src/state.py, pyproject.toml, tests/integration/conftest.py, tests/integration/test_charm.py, uv.lock
This PR fixes a race condition between `slurmctld` and `sackd` where `sackd` receives the _slurm.key_ secret and controllers list before the `slurmctld` service has started. This causes `sackd` units to fail because they will fail to retrieve the relevant configuration files from `slurmctld`.
To get around this issue, I introduced the `slurmctld_is_active` condition that defers the `SackdConnectedEvent` and …
=> fix(slurmctld): add `slurmctld_is_active` condition to prevent premature `sackd` service start

.github/workflows/backport.yaml, CONTRIBUTING.md
Adds a new Github action that backports the commits on PRs with the `backport` label. This automatically opens a PR with the changes to ensure every backport passes CI before merging it into maintained branches. 
Added maintainer documentation on how to use the new label.
=> ci: add action to backport PRs to branches

charms/slurmctld/src/constants.py
This PR enables `signalchildprocesses` by default in the _cgroup.conf_ configuration file so that child processes left behind by a completed job on a compute will be reapered by Slurm. This is an outstanding feature request that was blocked all the way back in 2024 because the apt charm library did not support Noble and this option was added in Slurm 23.02, but now, since it does, we can enable this configuration …
=> feat(slurmctld): enable `signalchildprocesses` by default
